### ISSUE TITLE
Name this thing

### ISSUE THREAD

**Issue by rnelson0** [commitmas/30-days-of-commitmas-2015#1]
@mjbrender Hrm, can't open issues on a fork! I cloned the 12 days, removed the origin, and then added this one and pushed it. Is the repo name good for this year?

**Comment by mbbroberg** [comment]
I'm good with it @rnelson0. Roll with it!

**Comment by jfrappier** [comment]
This feels more appropriate every day :)
http://www.explainxkcd.com/wiki/index.php/1597:_Git

**Comment by rnelson0** [comment]
Haha, it does! If there's a way to "split" a fork into a master, I haven't figured it out yet - but that's _technically_ a GitHub issue not a Git issue :)
